import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <nav className="h-8 bg-red-500">
          <Link href={"/contact"}>about me</Link>
          <Link href={"/register"}>register</Link>
          <Link href={"/farmers"}>farmers</Link>
        </nav>
        {children}
        <Toaster />
        <footer className="h-8 bg-blue-700">hi</footer>
      </body>
    </html>
  );
}
